name: news_app
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

# The version of your application.
version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Your added packages
  provider: ^6.1.2
  intl: ^0.19.0

  cupertino_icons: ^1.0.6
  firebase_core: ^3.2.0
  firebase_auth: ^5.1.2
  google_sign_in: ^6.2.1
  cloud_firestore: ^5.1.0
  firebase_storage: ^12.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

# The following section is specific to Flutter and should be left as is.
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg